[target.'cfg(target_os = "linux")']
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

# Patched versions because SurrealDB makes silly design decisions sometimes
[patch.crates-io]
surrealdb = { git = "https://github.com/disconsented/surrealdb.git", rev = "3475af9429c9ddcdf054c2be02c225abde0e7b3e" }
surrealdb-core = { git = "https://github.com/disconsented/surrealdb.git", rev = "3475af9429c9ddcdf054c2be02c225abde0e7b3e" }
surrealdb-types = { git = "https://github.com/disconsented/surrealdb.git", rev = "3475af9429c9ddcdf054c2be02c225abde0e7b3e" }
